import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { FEATURED_DECKS } from '../../lib/featured-decks'

test.describe('local account library', () => {
  test.skip(process.env.FIREBASE_E2E !== 'true', 'Requires a build in emulator mode and running local emulators.')

  async function openApp(page: Page) {
    await page.addInitScript(() => localStorage.setItem('pcd_has_seen_help', 'true'))
    await page.route('https://**/*', route => {
      // Firebase's popup helper loads Google's public API script even in emulator mode.
      const host = new URL(route.request().url()).hostname
      return host === 'apis.google.com' ? route.continue() : route.abort()
    })
    await page.goto('/')
    await page.getByRole('button', { name: 'Decline', exact: true }).click()
  }
  async function signIn(page: Page, email: string) {
    const popupReady = page.waitForEvent('popup')
    await page.getByRole('button', { name: 'Continue with Google' }).click()
    const popup = await popupReady
    // The emulator initially renders an uninitialized provider; wait before clicking.
    await popup.getByText('Sign-in with Google.com', { exact: true }).waitFor()
    await popup.getByText('Add new account', { exact: true }).click()
    await popup.locator('#email-input').fill(email)
    await popup.locator('#display-name-input').fill('Practice tester')
    await popup.getByRole('button', { name: 'Sign in with Google.com', exact: true }).click()
    await expect(page.getByRole('dialog').getByText(email,{exact:true})).toBeAttached()
    if(!await page.getByRole('button',{name:'Sign out',exact:true}).isVisible())await page.getByText('Account settings',{exact:true}).click()
    await expect(page.getByRole('dialog').getByText(email, { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled()
  }

  test('guest practice never initializes Firebase and library dialog is accessible', async ({ page }) => {
    const firebaseRequests: string[] = []
    page.on('request', request => { if (/:(8080|9099)\//.test(request.url())) firebaseRequests.push(request.url()) })
    await openApp(page)
    await page.getByRole('textbox', { name: 'Deck list', exact: true }).fill(FEATURED_DECKS[0].importText)
    await page.getByRole('button', { name: 'Import Deck', exact: true }).click()
    await expect(page.getByText('Deck ready', { exact: true })).toBeVisible()
    expect(firebaseRequests).toEqual([])
    await page.locator('#deck-library-trigger').click()
    await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeVisible()
    const result = await new AxeBuilder({ page }).include('[role="dialog"]').withRules(['button-name', 'aria-dialog-name', 'label', 'aria-valid-attr-value']).analyze()
    expect(result.violations).toEqual([])
    await page.keyboard.press('Escape')
    await expect(page.locator('#deck-library-trigger')).toBeFocused()
    await page.getByRole('button', { name: 'Start Game', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Guess Prizes', exact: true })).toBeVisible()
  })

  test('save, reload, account isolation, load, and delete work', async ({ page }, testInfo) => {
    test.setTimeout(90000)
    const email = `alice-${testInfo.project.name}-${Date.now()}@example.test`
    await openApp(page)
    await page.getByRole('textbox', { name: 'Deck list', exact: true }).fill(FEATURED_DECKS[0].importText)
    await page.getByRole('button', { name: 'Import Deck', exact: true }).click()
    await expect(page.getByText('Deck ready', { exact: true })).toBeVisible()
    await page.locator('#deck-library-trigger').click()
    await signIn(page, email)
    await page.getByRole('button', { name: 'Save current deck', exact: true }).click()
    await page.getByLabel('Save current imported deck', { exact: true }).fill('My practice deck')
    await page.getByRole('combobox', { name: 'Deck logo', exact: true }).selectOption({index:1})
    await page.getByRole('button', { name: 'Save deck', exact: true }).click()
    await expect(page.getByRole('dialog').getByText('My practice deck', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled()
    await page.getByRole('button', { name: 'Change logo for My practice deck', exact: true }).click()
    const logo = page.getByRole('button', { name: /^Use .+ as logo$/ }).first()
    await logo.click()
    await expect(page.getByText('Deck logo updated.', { exact: true })).toBeVisible()
    await page.getByLabel('Actions for My practice deck', { exact: true }).click()
    await page.getByRole('button', { name: 'Rename', exact: true }).click()
    await page.getByRole('textbox', { name: 'Deck name', exact: true }).fill('   ')
    await expect(page.getByRole('button', { name: 'Save name', exact: true })).toBeDisabled()
    await page.getByRole('textbox', { name: 'Deck name', exact: true }).fill('Updated practice deck')
    await page.getByRole('button', { name: 'Save name', exact: true }).click()
    await expect(page.getByText('Deck renamed.', { exact: true })).toBeVisible()
    await page.getByRole('searchbox').fill('no such deck')
    await expect(page.getByText('No matching decks.', { exact: true })).toBeVisible()
    await page.getByRole('searchbox').fill('updated')
    await expect(page.getByRole('dialog').getByText('Updated practice deck', { exact: true })).toBeVisible()
    await page.getByRole('searchbox').fill('')
    await page.screenshot({ path: testInfo.outputPath('library.png'), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await page.reload()
    await page.locator('#deck-library-trigger').click()
    await expect(page.getByRole('dialog').getByText('Updated practice deck', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Load deck', exact: true }).click()
    await expect(page.getByText('Deck ready', { exact: true })).toBeVisible()
    await page.getByRole('button',{name:'Edit full list'}).click()
    await expect(page.getByRole('textbox', { name: 'Deck list', exact: true })).toHaveValue(FEATURED_DECKS[0].importText)
    await page.locator('#deck-library-trigger').click()
    await page.getByText('Account settings',{exact:true}).click()
    await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeEnabled()
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await expect(page.getByRole('dialog').getByText('Updated practice deck', { exact: true })).toHaveCount(0)
    await signIn(page, `bob-${testInfo.project.name}-${Date.now()}@example.test`)
    await expect(page.getByText('No saved decks yet.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await signIn(page, email)
    await expect(page.getByRole('dialog').getByText('Updated practice deck', { exact: true })).toBeVisible()
    await page.getByLabel('Actions for Updated practice deck', { exact: true }).click()
    await page.getByRole('button', { name: 'Delete', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm delete', exact: true }).click()
    await expect(page.getByText('No saved decks yet.', { exact: true })).toBeVisible()
  })

  test('a storage outage reports an error without blocking guest practice', async ({ page }, testInfo) => {
    await openApp(page)
    await page.getByRole('textbox', { name: 'Deck list', exact: true }).fill(FEATURED_DECKS[0].importText)
    await page.getByRole('button', { name: 'Import Deck', exact: true }).click()
    await expect(page.getByText('Deck ready', { exact: true })).toBeVisible()
    await page.route('http://127.0.0.1:8080/**', route => route.abort())
    await page.locator('#deck-library-trigger').click()
    // This test intentionally waits for the bounded storage request to fail.
    const email = `offline-${testInfo.project.name}-${Date.now()}@example.test`
    const popupReady = page.waitForEvent('popup')
    await page.getByRole('button', { name: 'Continue with Google' }).click()
    const popup = await popupReady
    await popup.getByText('Sign-in with Google.com', { exact: true }).waitFor()
    await popup.getByText('Add new account', { exact: true }).click()
    await popup.locator('#email-input').fill(email)
    await popup.getByRole('button', { name: 'Sign in with Google.com', exact: true }).click()
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Could not reach your library', { timeout: 20000 })
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Start Game', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Guess Prizes', exact: true })).toBeVisible()
  })


  test('account progress keeps original revisions and supports replay', async ({page,browser},testInfo) => {
    test.setTimeout(90000)
    await openApp(page)
    await page.getByRole('textbox',{name:'Deck list',exact:true}).fill(FEATURED_DECKS[0].importText)
    await page.getByRole('button',{name:'Import Deck',exact:true}).click()
    await expect(page.getByText('Deck ready',{exact:true})).toBeVisible()
    await page.locator('#deck-library-trigger').click()
    const email=`history-${testInfo.project.name}-${Date.now()}@example.test`
    await signIn(page,email)
    await page.getByRole('button',{name:'Save current deck',exact:true}).click()
    await page.getByLabel('Save current imported deck',{exact:true}).fill('History deck')
    await page.getByRole('button',{name:'Save deck',exact:true}).click()
    await expect(page.getByText('Deck saved.',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:'Close',exact:true}).click()
    await page.getByRole('button',{name:'Start Game',exact:true}).click()
    await page.getByRole('button',{name:'Guess Prizes',exact:true}).click()
    const guesses=page.getByRole('button',{name:/, copy \d+$/})
    for(let i=0;i<6;i++)await guesses.nth(i).click()
    await page.getByRole('button',{name:'Submit Guesses',exact:true}).click()
    await page.keyboard.press('Escape')
    await expect(page.getByText('Saved to account',{exact:true})).toBeVisible()
    await page.reload()
    await page.getByRole('textbox',{name:'Deck list',exact:true}).fill(FEATURED_DECKS[1].importText)
    await page.getByRole('button',{name:'Import Deck',exact:true}).click()
    await expect(page.getByText('Deck ready',{exact:true})).toBeVisible()
    await page.locator('#deck-library-trigger').click()
    await expect(page.getByText('History deck',{exact:true})).toBeVisible()
    await page.getByLabel('Actions for History deck',{exact:true}).click()
    await page.getByRole('button',{name:'Update list',exact:true}).click()
    await page.getByRole('button',{name:'Confirm update',exact:true}).click()
    await expect(page.getByText('New revision saved.',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    await expect(page.getByRole('button',{name:'History deck'})).toContainText('History deck')
    await expect(page.getByRole('dialog')).toHaveCount(1)
    const name=page.getByRole('textbox',{name:'Deck name',exact:true})
    await name.fill('Shared name');await name.press('Enter')
    await expect(page.getByRole('button',{name:'History deck',exact:true})).toContainText('Shared name')
    await page.getByRole('button',{name:'Decks',exact:true}).click()
    await expect(page.getByRole('dialog').getByText('Shared name',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    const independent=await browser.newContext()
    const other=await independent.newPage();await openApp(other);await other.locator('#deck-library-trigger').click();await signIn(other,email)
    await expect(other.getByText('Shared name',{exact:true})).toBeVisible()
    await other.getByRole('button',{name:'Progress',exact:true}).click()
    await expect(other.getByText('1 comparable round',{exact:false})).toBeVisible()
    await independent.close()
    await page.getByRole('button',{name:'Practice this deck',exact:true}).click()
    await page.getByRole('button',{name:'Edit full list'}).click()
    await expect(page.getByRole('textbox',{name:'Deck list',exact:true})).toHaveValue(FEATURED_DECKS[0].importText)
    await expect(page.getByText('Deck ready',{exact:true})).toBeVisible()
  })

  test('guest transfer requires confirmation and does not duplicate records', async ({page},testInfo) => {
    await page.addInitScript(()=>localStorage.setItem('prizecheck:practice-history:v1',JSON.stringify([{id:'guest-transfer',deckKey:'guest-deck',deckName:'Guest deck',at:1000,scoringVersion:2,duration:120,correct:3,seconds:100,missed:[]} ])))
    await openApp(page)
    await page.locator('#deck-library-trigger').click()
    await signIn(page,`transfer-${testInfo.project.name}-${Date.now()}@example.test`)
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    await expect(page.getByText('Your progress starts with your first round.',{exact:true})).toBeVisible()
    if(!await page.getByRole('button',{name:'Transfer guest history',exact:true}).isVisible())await page.getByText('Device history',{exact:false}).first().click()
    await page.getByRole('button',{name:'Transfer guest history',exact:true}).click()
    await page.getByRole('button',{name:'Confirm transfer',exact:true}).click()
    await expect(page.getByText(/Guest rounds added/)).toBeVisible()
    if(!await page.getByRole('button',{name:'Transfer guest history',exact:true}).isVisible())await page.getByText('Device history',{exact:false}).first().click()
    await page.getByRole('button',{name:'Transfer guest history',exact:true}).click()
    await page.getByRole('button',{name:'Confirm transfer',exact:true}).click()
    await expect(page.getByText(/1 comparable round/)).toBeVisible()
  })


  test('account deletion removes decks, revisions and history after reauthentication', async ({page,request},testInfo) => {
    test.setTimeout(90000)
    let uid=''
    page.on('response', async response=>{if(response.url().includes('accounts:signInWithIdp')){try{const data=await response.json();if(data.localId)uid=data.localId}catch{}}})
    await openApp(page)
    await page.getByRole('textbox',{name:'Deck list',exact:true}).fill(FEATURED_DECKS[0].importText)
    await page.getByRole('button',{name:'Import Deck',exact:true}).click()
    await expect(page.getByText('Deck ready',{exact:true})).toBeVisible()
    await page.locator('#deck-library-trigger').click()
    const email=`delete-${testInfo.project.name}-${Date.now()}@example.test`
    await signIn(page,email)
    await page.getByRole('button',{name:'Save current deck',exact:true}).click()
    await page.getByLabel('Save current imported deck',{exact:true}).fill('Delete me')
    await page.getByRole('button',{name:'Save deck',exact:true}).click()
    await expect(page.getByText('Deck saved.',{exact:true})).toBeVisible()
    await page.getByLabel('Actions for Delete me',{exact:true}).click()
    await page.getByRole('button',{name:'Update list',exact:true}).click()
    await page.getByRole('button',{name:'Confirm update',exact:true}).click()
    await expect(page.getByText('New revision saved.',{exact:true})).toBeVisible()
    await page.evaluate(()=>localStorage.setItem('prizecheck:practice-history:v1',JSON.stringify([{id:'delete-round',deckKey:'delete-deck',deckName:'Delete history',at:1000,scoringVersion:2,duration:120,correct:0,seconds:120,missed:[]} ])))
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    if(!await page.getByRole('button',{name:'Transfer guest history',exact:true}).isVisible())await page.getByText('Device history',{exact:false}).first().click()
    await page.getByRole('button',{name:'Transfer guest history',exact:true}).click()
    await page.getByRole('button',{name:'Confirm transfer',exact:true}).click()
    await expect(page.getByText(/Guest rounds added/)).toBeVisible()
    await expect.poll(()=>uid).not.toBe('')
    const base=`http://127.0.0.1:8080/v1/projects/demo-prizecheck/databases/(default)/documents/users/${uid}`
    const before=await (await request.get(`${base}/decks`,{headers:{Authorization:'Bearer owner'}})).json()
    const deckId=before.documents[0].name.split('/').at(-1)
    await page.getByRole('button',{name:'Delete account',exact:true}).click()
    const popupReady=page.waitForEvent('popup')
    await page.getByRole('button',{name:'Confirm account deletion',exact:true}).click()
    const popup=await popupReady
    await popup.getByText('Sign-in with Google.com',{exact:true}).waitFor()
    // Reuse the provider identity for reauthentication; creating another fake
    // provider identity for the same email leaves a stale index in the emulator.
    await popup.locator('.js-reuse-account').filter({hasText:email}).click()
    await expect(page.getByRole('button',{name:'Continue with Google',exact:true})).toBeVisible()
    for(const path of ['decks',`decks/${deckId}/versions`,'sessions']) {
      const data=await (await request.get(`${base}/${path}`,{headers:{Authorization:'Bearer owner'}})).json()
      expect(data.documents || []).toHaveLength(0)
    }
  })

  test('pending rounds survive offline reload and reconnect once',async({page,browser},info)=>{
    test.setTimeout(90000)
    await openApp(page);await page.locator('#deck-library-trigger').click()
    const email=`queue-${info.project.name}-${Date.now()}@example.test`
    await signIn(page,email)
    await page.evaluate(()=>localStorage.setItem('prizecheck:practice-history:v1',JSON.stringify([{id:'offline-round',deckKey:'offline-deck',deckName:'Offline deck',at:1,scoringVersion:2,duration:120,correct:3,seconds:80,missed:[]} ])))
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    await page.getByText('Device history',{exact:false}).first().click()
    await page.route('http://127.0.0.1:8080/**',route=>route.abort())
    await page.getByRole('button',{name:'Transfer guest history',exact:true}).click()
    await page.getByRole('button',{name:'Confirm transfer',exact:true}).click()
    await expect(page.getByText(/Guest rounds added/)).toBeVisible()
    await page.reload();await page.locator('#deck-library-trigger').click()
    await expect(page.getByRole('dialog').getByText(email,{exact:true})).toBeAttached()
    await page.getByRole('button',{name:'Progress',exact:true}).click()
    await expect(page.getByText('1 comparable round',{exact:false})).toBeVisible()
    await page.unroute('http://127.0.0.1:8080/**')
    await page.evaluate(()=>window.dispatchEvent(new Event('online')))
    await expect(page.getByText('Saved',{exact:true})).toBeVisible()
    const context=await browser.newContext(),other=await context.newPage()
    await openApp(other);await other.locator('#deck-library-trigger').click();await signIn(other,email)
    await other.getByRole('button',{name:'Progress',exact:true}).click()
    await expect(other.getByText('1 comparable round',{exact:false})).toBeVisible()
    await context.close()
  })

})
